allowBuilds:
  core-js: true
  esbuild: true
  protobufjs: true
  svelte-preprocess: true
minimumReleaseAgeExclude:
  - prettier-plugin-svelte@4.0.0
  - vite@8.0.14
  - '@sveltecraft/sandbox@0.0.1'
onlyBuiltDependencies:
  - core-js
  - esbuild
  - protobufjs
  - svelte-preprocess
